# Generated by Django 4.2.4 on 2023-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedido', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='usuario_table')),
                ('dni', models.CharField(max_length=13, unique=True, verbose_name='dni')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=250, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=250, verbose_name='apellido_materno')),
                ('fecha_naciemento', models.DateField(null=True, verbose_name='fecha_naciemento')),
                ('direccion', models.CharField(max_length=250, null=True, verbose_name='direccion')),
                ('numero_celular', models.CharField(max_length=14, verbose_name='numero_celular')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, null=True)),
                ('roles_usuario', models.CharField(choices=[('U', 'usuario'), ('A', 'administrador')], default='U', max_length=1)),
                ('codregistro', models.CharField(blank=True, max_length=6)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('usuario_pedido', models.ManyToManyField(to='Pedido.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
