# Generated by Django 4.2.4 on 2023-11-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Platos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha_creacion')),
                ('precio_total', models.FloatField(default=0, verbose_name='precio_total')),
                ('pedido_cancelado', models.BooleanField(default=False, null=True)),
                ('metodo_pago', models.ImageField(null=True, upload_to='pedido')),
            ],
        ),
        migrations.CreateModel(
            name='pedido_plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platos.platos')),
            ],
        ),
    ]
