# Generated by Django 4.2.4 on 2023-11-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=1500, verbose_name='pregunta_al_bot')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasGnericas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes')),
                ('musica', models.FileField(blank=True, max_length=250, upload_to='mp3')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.preguntachat')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chatbot.respuestasgnericas')),
            ],
        ),
    ]
