# Generated by Django 4.2.4 on 2023-11-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespuestasGnericas',
            new_name='RespuestasGenericas',
        ),
    ]
